
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

title: Akaseon Study Note
email: akaseon@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 5

github:
  repo: 'https://github.com/akaseon'
github_username: akaseon

# Build settings
#markdown: kramdown
#theme: minima
theme: lanyon

plugins:
  - jekyll-paginate

category_dir: category/
tag_dir: tag/

excerpt_separator: ""

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
